apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: {{ component_name }}
  annotations:
    description: "NATS messaging to keyvalue sync example"
    wasmcloud.dev/authors: wasmCloud team
    wasmcloud.dev/source-url: https://github.com/wasmCloud/go/blob/main/examples/components/nats-to-nats-kv/wadm.yaml
    wasmcloud.dev/readme-md-url: https://github.com/wasmCloud/go/blob/main/examples/components/nats-to-nats-kv/README.md
    wasmcloud.dev/homepage: https://github.com/wasmCloud/go/blob/main/examples/components/nats-to-nats-kv
    wasmcloud.dev/categories: |
      nats,messaging,keyvalue,tinygo,golang,example
spec:
  components:
  - name: {{ component_name }}
    type: component
    properties:
      image: {{ registry_url }}/{{ component_name }}:{{ version }}
    traits:
    - type: link
      properties:
        namespace: wasi
        package: keyvalue
        interfaces:
        - store
        target:
          name: keyvalue-nats
          config:
          - name: default
            properties:
              bucket: {{ bucket }}
              enable_bucket_auto_create: 'true'
              js_domain: {{ js_domain }}
    - type: spreadscaler
      properties:
        instances: 1
        spread:
        {%- set weight = (100 / (targets | length)) | int -%}
        {% for target in targets %}
        - name: {{ target }}
          weight: {{ weight }}
          requirements:
            host-type: {{ target }}
        {% endfor %}

  - name: keyvalue-nats
    type: capability
    properties:
      image: ghcr.io/wasmcloud/keyvalue-nats:0.3.1
      config:
        - name: default
          properties:
            js_domain: {{ js_domain }}
    traits:
      - type: spreadscaler
        properties:
          instances: 1
          spread:
          {%- set weight = (100 / (targets | length)) | int -%}
          {% for target in targets %}
          - name: {{ target }}
            weight: {{ weight }}
            requirements:
              host-type: {{ target }}
          {% endfor %}
  - name: messaging-nats
    type: capability
    properties:
      image: ghcr.io/wasmcloud/messaging-nats:0.24.0
    traits:
      - type: link
        properties:
          target: {{ component_name }}
          namespace: wasmcloud
          package: messaging
          interfaces: [handler]
          source_config:
            - name: simple-subscription
              properties:
                subscriptions: {{ source_topic}}
                js_domain: {{ js_domain }}
      - type: spreadscaler
        properties:
          instances: 1
          spread:
          {%- set weight = (100 / (targets | length)) | int -%}
          {% for target in targets %}
          - name: {{ target }}
            weight: {{ weight }}
            requirements:
              host-type: {{ target }}
          {% endfor %}