apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: "nats-to-nats-kv"
  annotations:
    description: "NATS messaging to keyvalue sync example"
    wasmcloud.dev/authors: wasmCloud team
    wasmcloud.dev/source-url: https://github.com/wasmCloud/go/blob/main/examples/components/nats-to-nats-kv/wadm.yaml
    wasmcloud.dev/readme-md-url: https://github.com/wasmCloud/go/blob/main/examples/components/nats-to-nats-kv/README.md
    wasmcloud.dev/homepage: https://github.com/wasmCloud/go/blob/main/examples/components/nats-to-nats-kv
    wasmcloud.dev/categories: |
      nats,messaging,keyvalue,tinygo,golang,example
spec:
  components:
  - name: keyvalue-nats
    type: capability
    properties:
      image: ghcr.io/wasmcloud/keyvalue-nats:0.3.1
    traits: []
  - name: messaging-nats
    type: capability
    properties:
      image: ghcr.io/wasmcloud/messaging-nats:0.24.0
    traits:
      - type: link
        properties:
          target: nats-to-nats-kv
          namespace: wasmcloud
          package: messaging
          interfaces: [handler]
          source_config:
            - name: simple-subscription
              properties:
                subscriptions: test.example
  - name: nats-to-nats-kv
    type: component
    properties:
      image: file://./build/nats-keyvalue-sync_s.wasm
      id: nats-kv-handler
    traits:
    - type: spreadscaler
      properties:
        instances: 1
    - type: link
      properties:
        namespace: wasi
        package: keyvalue
        interfaces:
        - store
        target:
          name: keyvalue-nats
          config:
          - name: wasi-keyvalue-config
            properties:
              bucket: test-keyvalue
              enable_bucket_auto_create: 'true'
