package wasmcloud:default;

world default {
  include wasmcloud:component-go/imports@0.1.0;

  import wasi:config/runtime@0.2.0-draft;

  export wasi:http/incoming-handler@0.2.0;

  export wasmcloud:messaging/handler@0.2.0;
  import wasmcloud:messaging/consumer@0.2.0;
  import wasi:logging/logging@0.1.0-draft;
}
